# PyTorch

<img src="https://raw.githubusercontent.com/LisonEvf/practicalAI-cn/master/images/logo.png" width=150>

在这节课中，我们将学习PyTorch，它是一个用于构建动态神经网络的学习库。我们将在本课程中了解其基础知识，以及如何创建和使用张量（Tensor），而我们将在下一课中使用它制作模型。

<img src="https://raw.githubusercontent.com/LisonEvf/practicalAI-cn/master/images/pytorch.png" width=300>

# Tensor 基础知识

In [39]:
# 安装PyTorch库
!pip3 install torch

>  注意：上述安装PyTorch的方式与官网并不一致，因为这里是基于Colab云端安装的，而大家一般是使用pip或者conda来安装PyTorch。具体安装教程参考：https://pytorch.org/

In [40]:
import numpy as np
import torch

In [41]:
# 创建一个张量
x = torch.Tensor(3, 4)
print("Type: {}".format(x.type()))
print("Size: {}".format(x.shape))
print("Values: \n{}".format(x))

Type: torch.FloatTensor
Size: torch.Size([3, 4])
Values: 
tensor([[2.1707e-18, 7.0952e+22, 1.7748e+28, 1.8176e+31],
        [7.2708e+31, 5.0778e+31, 3.2608e-12, 1.7728e+28],
        [7.0367e+22, 2.1715e-18, 1.0741e-05, 5.2303e+22]])


In [42]:
# 创建一个随机张量
x = torch.randn(2, 3) # torch.randn对应于正态分布，而rand(2,3)对应于均匀分布
print (x)

tensor([[-1.1444, -2.3048,  1.3223],
        [ 0.0240,  1.3036, -0.8598]])


In [43]:
# 0和1张量
x = torch.zeros(2, 3)
print (x)
x = torch.ones(2, 3)
print (x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [44]:
# 列表（List） → 张量
x = torch.Tensor([[1, 2, 3],[4, 5, 6]])
print("Size: {}".format(x.shape))
print("Values: \n{}".format(x))

Size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [45]:
# NumPy 数组 → 张量
x = torch.from_numpy(np.random.rand(2, 3))
print("Size: {}".format(x.shape))
print("Values: \n{}".format(x))

Size: torch.Size([2, 3])
Values: 
tensor([[0.6959, 0.0265, 0.3545],
        [0.3121, 0.6025, 0.1110]], dtype=torch.float64)


In [46]:
# 改变张量类型（张量默认为float类型）
x = torch.Tensor(3, 4)
print("Type: {}".format(x.type()))
x = x.long()
print("Type: {}".format(x.type()))

Type: torch.FloatTensor
Type: torch.LongTensor


# Tensor 运算

In [47]:
# 加法
x = torch.randn(2, 3)
y = torch.randn(2, 3)
z = x + y
print("Size: {}".format(z.shape))
print("Values: \n{}".format(z))

Size: torch.Size([2, 3])
Values: 
tensor([[ 0.0126,  0.2411,  0.1714],
        [-0.1652, -0.2868,  0.6245]])


In [48]:
# Perform matrix multiplication
x = torch.randn(2, 3)
y = torch.randn(3, 2)
z = torch.mm(x, y)
print("Size: {}".format(z.shape))
print("Values: \n{}".format(z))

Size: torch.Size([2, 2])
Values: 
tensor([[-0.8347,  1.4113],
        [ 0.3776, -0.3886]])


In [49]:
# 转置
x = torch.randn(2, 3)
print("Size: {}".format(x.shape))
print("Values: \n{}".format(x))
y = torch.t(x)
print("Size: {}".format(y.shape))
print("Values: \n{}".format(y))

Size: torch.Size([2, 3])
Values: 
tensor([[-0.2393, -0.8744, -0.3205],
        [ 0.4165,  0.3642, -0.7121]])
Size: torch.Size([3, 2])
Values: 
tensor([[-0.2393,  0.4165],
        [-0.8744,  0.3642],
        [-0.3205, -0.7121]])


In [50]:
# Reshape
z = x.view(3, 2)
print("Size: {}".format(z.shape))
print("Values: \n{}".format(z))

Size: torch.Size([3, 2])
Values: 
tensor([[-0.2393, -0.8744],
        [-0.3205,  0.4165],
        [ 0.3642, -0.7121]])


In [51]:
# reshaping的危险（意外后果）
x = torch.tensor([
    [[1,1,1,1], [2,2,2,2], [3,3,3,3]],
    [[10,10,10,10], [20,20,20,20], [30,30,30,30]]
])
print("Size: {}".format(x.shape))
print("Values: \n{}\n".format(x))
a = x.view(x.size(1), -1)
print("Size: {}".format(a.shape))
print("Values: \n{}\n".format(a))
b = x.transpose(0,1).contiguous()
print("Size: {}".format(b.shape))
print("Values: \n{}\n".format(b))
c = b.view(b.size(0), -1)
print("Size: {}".format(c.shape))
print("Values: \n{}".format(c))

Size: torch.Size([2, 3, 4])
Values: 
tensor([[[ 1,  1,  1,  1],
         [ 2,  2,  2,  2],
         [ 3,  3,  3,  3]],

        [[10, 10, 10, 10],
         [20, 20, 20, 20],
         [30, 30, 30, 30]]])

Size: torch.Size([3, 8])
Values: 
tensor([[ 1,  1,  1,  1,  2,  2,  2,  2],
        [ 3,  3,  3,  3, 10, 10, 10, 10],
        [20, 20, 20, 20, 30, 30, 30, 30]])

Size: torch.Size([3, 2, 4])
Values: 
tensor([[[ 1,  1,  1,  1],
         [10, 10, 10, 10]],

        [[ 2,  2,  2,  2],
         [20, 20, 20, 20]],

        [[ 3,  3,  3,  3],
         [30, 30, 30, 30]]])

Size: torch.Size([3, 8])
Values: 
tensor([[ 1,  1,  1,  1, 10, 10, 10, 10],
        [ 2,  2,  2,  2, 20, 20, 20, 20],
        [ 3,  3,  3,  3, 30, 30, 30, 30]])


In [52]:
# 维度操作
x = torch.randn(2, 3)
print("Values: \n{}".format(x))
y = torch.sum(x, dim=0) # 为每列添加各行叠加的值
print("Values: \n{}".format(y))
z = torch.sum(x, dim=1) # 为每行添加各列叠加的值
print("Values: \n{}".format(z))

Values: 
tensor([[-0.8829,  1.0314,  1.1152],
        [ 1.3328, -0.5288, -0.4849]])
Values: 
tensor([0.4500, 0.5026, 0.6303])
Values: 
tensor([1.2638, 0.3191])


# 索引，切片和级联

In [53]:
x = torch.randn(3, 4)
print("x: \n{}".format(x))
print ("x[:1]: \n{}".format(x[:1]))
print ("x[:1, 1:3]: \n{}".format(x[:1, 1:3]))

x: 
tensor([[-0.4221, -0.6034,  0.4719,  0.9994],
        [ 0.5991, -0.5578,  1.1728, -1.6195],
        [ 0.8985,  0.9652,  0.3019,  1.6295]])
x[:1]: 
tensor([[-0.4221, -0.6034,  0.4719,  0.9994]])
x[:1, 1:3]: 
tensor([[-0.6034,  0.4719]])


In [54]:
# 选择维度索引
x = torch.randn(2, 3)
print("Values: \n{}".format(x))
col_indices = torch.LongTensor([0, 2])
chosen = torch.index_select(x, dim=1, index=col_indices) # 第0和第2列的值
print("Values: \n{}".format(chosen))
row_indices = torch.LongTensor([0, 1])
chosen = x[row_indices, col_indices] # 来自（0,0）和（2,1）的值
print("Values: \n{}".format(chosen))

Values: 
tensor([[-0.7936, -0.3918, -0.5397],
        [ 1.5769, -0.8620, -0.0521]])
Values: 
tensor([[-0.7936, -0.5397],
        [ 1.5769, -0.0521]])
Values: 
tensor([-0.7936, -0.0521])


In [55]:
# 级联
x = torch.randn(2, 3)
print("Values: \n{}".format(x))
y = torch.cat([x, x], dim=0) # 按行堆叠（dim = 1按列堆叠）
print("Values: \n{}".format(y))

Values: 
tensor([[-0.0831, -0.4073, -0.3241],
        [ 1.4726, -1.0771,  0.1149]])
Values: 
tensor([[-0.0831, -0.4073, -0.3241],
        [ 1.4726, -1.0771,  0.1149],
        [-0.0831, -0.4073, -0.3241],
        [ 1.4726, -1.0771,  0.1149]])


# 梯度

In [56]:
# 带有gradient bookkeeping的张量
x = torch.rand(3, 4, requires_grad=True)
y = 3*x + 2
z = y.mean()
z.backward() # z是标量
print("Values: \n{}".format(x))
print("x.grad: \n", x.grad)

Values: 
tensor([[0.8508, 0.8208, 0.7108, 0.7867],
        [0.7515, 0.2599, 0.7063, 0.0660],
        [0.0072, 0.4243, 0.7172, 0.5873]], requires_grad=True)
x.grad: 
 tensor([[0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500]])


* $ y = 3x + 2 $
* $ z = \sum{y}/N $
* $ \frac{\partial(z)}{\partial(x)} = \frac{\partial(z)}{\partial(y)} \frac{\partial(z)}{\partial(x)} = \frac{1}{N} * 3 = \frac{1}{12} * 3 = 0.25 $

# CUDA 张量

In [57]:
# CUDA可用吗？
print (torch.cuda.is_available())

True


如果上面的代码返回False，那么请转到菜单栏上的`Runtime`→`Change runtime type`并在`Hardware accelerator`下选择`GPU`。

In [58]:
# 创建一个CPU版的0张量
x = torch.Tensor(3, 4).to("cpu")
print("Type: {}".format(x.type()))

Type: torch.FloatTensor


In [59]:
# 创建一个CUDA版的0张量
x = torch.Tensor(3, 4).to("cuda")
print("Type: {}".format(x.type()))

Type: torch.cuda.FloatTensor
